macros: remove macro tests
Using the serde_yaml deserializer means we don't need to check for
deserialization errors ourselves, and checking whether the macro
actually works isn't feasible either with our approach:

I get the following error when trying to run a `trybuild` test that
should compile, because we use CARGO_MANIFEST_DIR to find the
config.yaml file, and it happens somewhere inside the target directory
during tests:

error: proc macro panicked
 --> $DIR/pass.rs:4:5
  |
4 |     gateway_config!("config.yaml")
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: Failed to read `$WORKSPACE/target/tests/macros/config.yaml`: No such file or directory (os error 2)